// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHX3-IegbWgriYiaZB5axZf_BqZQC5Nls',
    appId: '1:960243657636:web:c7ca25bc675f698ccfaf31',
    messagingSenderId: '960243657636',
    projectId: 'campus-cush',
    authDomain: 'campus-cush.firebaseapp.com',
    storageBucket: 'campus-cush.firebasestorage.app',
    measurementId: 'G-EQFHSD2ZWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHRqb2-dFiefE606DKsLcBz5kA95sEJI',
    appId: '1:960243657636:android:b14c643bb69e4343cfaf31',
    messagingSenderId: '960243657636',
    projectId: 'campus-cush',
    storageBucket: 'campus-cush.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCynHslDGHNozaIfcAco7G5nzKTMTSG1zo',
    appId: '1:960243657636:ios:87ba6fa8cda4b6f9cfaf31',
    messagingSenderId: '960243657636',
    projectId: 'campus-cush',
    storageBucket: 'campus-cush.firebasestorage.app',
    iosBundleId: 'com.example.campusCushConsumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCynHslDGHNozaIfcAco7G5nzKTMTSG1zo',
    appId: '1:960243657636:ios:87ba6fa8cda4b6f9cfaf31',
    messagingSenderId: '960243657636',
    projectId: 'campus-cush',
    storageBucket: 'campus-cush.firebasestorage.app',
    iosBundleId: 'com.example.campusCushConsumer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHX3-IegbWgriYiaZB5axZf_BqZQC5Nls',
    appId: '1:960243657636:web:d88a577fb1097faccfaf31',
    messagingSenderId: '960243657636',
    projectId: 'campus-cush',
    authDomain: 'campus-cush.firebaseapp.com',
    storageBucket: 'campus-cush.firebasestorage.app',
    measurementId: 'G-V8MR88HLYS',
  );
}
